/*
 * LoongArch first user process creation + minimal ELF loader.
 *
 * la_proc_make_first():
 *   1. Build the initcode binary (embedded in kernel) into a user page.
 *   2. Set up a user page table with code + stack pages.
 *   3. Create a user process with the right trap frame.
 *
 * The initcode binary is compiled from src/user/initcode_la.c with
 * the LoongArch toolchain and linked at address 0 (raw binary).
 * The kernel loads it at user VA 0x1000.
 */
#include "early_boot.h"
#include "proc.h"
#include "trap.h"

/* ---- PTE permission flags (LoongArch TLBELO format) ----
 *   V=bit0, D=bit1, PLV=bits[3:2], P=bit7
 *   User RWX: V|D|PLV=3|P = 0x01|0x02|0x0C|0x80 = 0x8F
 */
#define EXE_PTE_U_RWX  0x8FUL

/* ---- LoongArch ELF header constants ---- */
#define LA_ELF_MAGIC   0x464C457FUL   /* "\x7fELF" */
#define LA_ELF_CLASS64 2
#define LA_ELF_DATA2LSB 1
#define LA_ELF_EXEC    2
#define LA_EM_LOONGARCH 0x102         /* EM_LOONGARCH */
#define LA_ELF_PROG_LOAD 1

/* ELF header (64-bit, little-endian) */
struct la_elf_ehdr {
    uint8_t  e_ident[16];
    uint16_t e_type;
    uint16_t e_machine;
    uint32_t e_version;
    uint64_t e_entry;
    uint64_t e_phoff;
    uint64_t e_shoff;
    uint32_t e_flags;
    uint16_t e_ehsize;
    uint16_t e_phentsize;
    uint16_t e_phnum;
    uint16_t e_shentsize;
    uint16_t e_shnum;
    uint16_t e_shstrndx;
};

/* ELF program header */
struct la_elf_phdr {
    uint32_t p_type;
    uint32_t p_flags;
    uint64_t p_offset;
    uint64_t p_vaddr;
    uint64_t p_paddr;
    uint64_t p_filesz;
    uint64_t p_memsz;
    uint64_t p_align;
};

/* ---- Embedded initcode binary (generated by build system) ---- */
#include "initcode_la.h"

#define initcode_la      target_loongarch_initcode_la
#define initcode_la_len  target_loongarch_initcode_la_len

/* ---- Forward declarations ---- */
extern uint64_t la_user_pgd;
extern uint64_t la_trap_ksp;

/*
 * Create the first user process from the embedded initcode.
 * Called from boot.c during kernel initialization.
 */
void la_proc_make_first(void)
{
    la_uart_puts("[initcode] creating first user process\n");

    /* 1. Create a user process (allocates proc slot + kernel stack) */
    struct la_proc *p = la_proc_create_user("initcode");
    if (!p) {
        la_uart_puts("[initcode] failed to create user proc\n");
        return;
    }

    /* 2. Create user page table */
    uint64_t *pgtbl = la_uvm_create();
    if (!pgtbl) {
        la_uart_puts("[initcode] failed to create page table\n");
        return;
    }
    p->pgtbl = pgtbl;

    /* 3. Allocate and map pages for initcode at VA 0x1000 */
    uint32_t code_size = initcode_la_len;
    uint32_t code_pages = (code_size + LA_PGSIZE - 1) / LA_PGSIZE;
    for (uint32_t i = 0; i < code_pages; i++) {
        if (la_uvm_alloc_page(pgtbl, LA_USER_BASE + i * LA_PGSIZE,
                               EXE_PTE_U_RWX) == 0) {
            la_uart_puts("[initcode] failed to allocate code page\n");
            return;
        }
    }

    /* 4. Copy initcode binary into the code pages */
    la_uvm_copy_in(pgtbl, LA_USER_BASE, initcode_la, code_size);

    /* 5. Allocate and map a user stack page */
    uint64_t stack_top = LA_USER_STACK;
    uint64_t stack_base = stack_top - LA_PGSIZE;
    uint64_t stack_pa = la_uvm_alloc_page(pgtbl, stack_base,
                                           EXE_PTE_U_RWX);
    if (!stack_pa) {
        la_uart_puts("[initcode] failed to allocate stack page\n");
        return;
    }

    /* 6. Set up the trap frame in a SEPARATE page (not on the kernel stack,
     *    because the bootstrap function's stack growth would overwrite it). */
    struct la_trap_frame *tf;
    tf = (struct la_trap_frame *)la_pmem_alloc();
    if (!tf) {
        la_uart_puts("[initcode] failed to allocate trap frame page\n");
        return;
    }
    p->tf = tf;

    /* Zero the trap frame */
    uint64_t *dst = (uint64_t *)tf;
    uint64_t *end = (uint64_t *)(tf + 1);
    while (dst < end)
        *dst++ = 0;

    /* Set entry point and stack pointer */
    tf->era = LA_USER_BASE;           /* entry point = code start */
    tf->gpr[LA_GPR_SP] = stack_top;   /* user stack pointer */
    tf->gpr[LA_GPR_A0] = 0;           /* argc = 0 */
    tf->gpr[LA_GPR_A1] = 0;           /* argv = NULL */

    /* Initialize fd table: stdin/stdout/stderr = console */
    p->fds[0].type = LA_FD_CONSOLE;
    p->fds[0].writable = 0;
    p->fds[1].type = LA_FD_CONSOLE;
    p->fds[1].writable = 1;
    p->fds[2].type = LA_FD_CONSOLE;
    p->fds[2].writable = 1;

    /* Set cwd to root inode */
    p->cwd_ino = la_fs_is_sea() ? 0 : 2;  /* SeaFS root=0, EXT4 root=2 */

    la_uart_puts("[initcode] trap frame at ");
    la_uart_put_hex((uint64_t)tf);
    la_uart_puts(" era=");
    la_uart_put_hex(tf->era);
    la_uart_puts(" sp=");
    la_uart_put_hex(tf->gpr[LA_GPR_SP]);
    la_uart_puts("\n");

    la_uart_puts("[initcode] first user process ready\n");
}

/*
 * Load a LoongArch ELF from the filesystem and create a user process.
 * This is the exec equivalent — replaces the current process's address space.
 *
 * For now, this is a minimal implementation:
 *   - Reads ELF from filesystem by inode number
 *   - Loads PT_LOAD segments into user pages
 *   - Sets up trap frame
 *
 * Returns 0 on success, -1 on failure.
 */
int la_do_exec(uint32_t ino, uint64_t entry_override)
{
    struct la_proc *p = la_current_proc();
    if (!p) return -1;

    /* Read ELF header */
    struct la_elf_ehdr eh;
    uint32_t n = la_fs_read_file(ino, 0, &eh, sizeof(eh));
    if (n != sizeof(eh)) {
        la_uart_puts("  exec: failed to read ELF header\n");
        return -1;
    }

    /* Verify ELF magic */
    if (*((uint32_t *)eh.e_ident) != LA_ELF_MAGIC) {
        la_uart_puts("  exec: bad ELF magic: ");
        la_uart_put_hex(*((uint32_t *)eh.e_ident));
        la_uart_puts("\n");
        return -1;
    }

    /* Verify LoongArch */
    if (eh.e_machine != LA_EM_LOONGARCH) {
        la_uart_puts("  exec: not LoongArch ELF (machine=");
        la_uart_put_hex(eh.e_machine);
        la_uart_puts(")\n");
        return -1;
    }

    la_uart_puts("  exec: valid LoongArch ELF, entry=");
    la_uart_put_hex(eh.e_entry);
    la_uart_puts(" phnum=");
    la_uart_put_hex(eh.e_phnum);
    la_uart_puts("\n");

    /* Create new page table */
    uint64_t *new_pgtbl = la_uvm_create();
    if (!new_pgtbl) return -1;

    /* Load PT_LOAD segments */
    for (int i = 0; i < eh.e_phnum; i++) {
        struct la_elf_phdr ph;
        uint64_t ph_off = eh.e_phoff + i * eh.e_phentsize;
        n = la_fs_read_file(ino, ph_off, &ph, sizeof(ph));
        if (n != sizeof(ph)) goto fail;

        if (ph.p_type != LA_ELF_PROG_LOAD)
            continue;

        if (ph.p_memsz == 0)
            continue;

        la_uart_puts("  exec: segment va=");
        la_uart_put_hex(ph.p_vaddr);
        la_uart_puts(" filesz=");
        la_uart_put_hex(ph.p_filesz);
        la_uart_puts(" memsz=");
        la_uart_put_hex(ph.p_memsz);
        la_uart_puts("\n");

        /* Map pages for this segment */
        uint64_t va = ph.p_vaddr & ~0xFFFUL;
        uint64_t va_end = (ph.p_vaddr + ph.p_memsz + 0xFFF) & ~0xFFFUL;
        for (; va < va_end; va += LA_PGSIZE) {
            if (la_uvm_alloc_page(new_pgtbl, va, EXE_PTE_U_RWX) == 0)
                goto fail;
        }

        /* Read segment data from filesystem into user pages */
        if (ph.p_filesz > 0) {
            /* Read in chunks (temp buffer approach) */
            uint64_t seg_off = 0;
            while (seg_off < ph.p_filesz) {
                uint32_t chunk = 512;
                if (chunk > ph.p_filesz - seg_off)
                    chunk = (uint32_t)(ph.p_filesz - seg_off);

                static __attribute__((aligned(8))) char tmpbuf[512];
                n = la_fs_read_file(ino, ph.p_offset + seg_off,
                                    tmpbuf, chunk);
                if (n != chunk) goto fail;

                la_uvm_copy_in(new_pgtbl, ph.p_vaddr + seg_off,
                               tmpbuf, chunk);
                seg_off += chunk;
            }
        }
    }

    /* Allocate stack */
    uint64_t stack_top = LA_USER_STACK;
    uint64_t stack_base = stack_top - LA_PGSIZE;
    if (la_uvm_alloc_page(new_pgtbl, stack_base, EXE_PTE_U_RWX) == 0)
        goto fail;

    /* Update process */
    /* TODO: free old page table */
    p->pgtbl = new_pgtbl;

    /* Reset trap frame */
    struct la_trap_frame *tf;
    tf = (struct la_trap_frame *)(p->kstack + LA_KSTACK_SIZE
                                  - sizeof(struct la_trap_frame));
    p->tf = tf;

    uint64_t *d = (uint64_t *)tf;
    uint64_t *e = (uint64_t *)(tf + 1);
    while (d < e) *d++ = 0;

    tf->era = entry_override ? entry_override : eh.e_entry;
    tf->gpr[LA_GPR_SP] = stack_top;
    tf->gpr[LA_GPR_A0] = 0;
    tf->gpr[LA_GPR_A1] = 0;

    /* Save kernel SP for trap handler */
    la_trap_ksp = p->kstack + LA_KSTACK_SIZE;

    /* Return to user mode via la_user_return */
    la_uvm_switch(p->pgtbl);
    la_user_return(tf);

    /* Should not reach here */
    return 0;

fail:
    /* TODO: free new_pgtbl pages */
    la_uart_puts("  exec: failed\n");
    return -1;
}

/*
 * Exec from syscall context.
 *
 * path  - kernel-space path string (already copied from user)
 * uargv - user-space pointer to argv array (char*[])
 *
 * This function:
 *   1. Resolves path to inode
 *   2. Loads ELF (reusing la_do_exec internals)
 *   3. Sets up user stack with argc/argv
 *   4. Switches to user mode (never returns on success)
 */
uint64_t la_do_exec_syscall(struct la_trap_frame *tf, const char *path,
                             uint64_t uargv)
{
    struct la_proc *p = la_current_proc();
    if (!p) return (uint64_t)-1;

    /* Resolve path to inode */
    uint32_t ino;
    if (la_fs_lookup((char *)path, &ino) < 0)
        return (uint64_t)-1;

    /* Read ELF header */
    struct la_elf_ehdr eh;
    uint32_t n = la_fs_read_file(ino, 0, &eh, sizeof(eh));
    if (n != sizeof(eh))
        return (uint64_t)-1;

    if (*((uint32_t *)eh.e_ident) != LA_ELF_MAGIC)
        return (uint64_t)-1;

    if (eh.e_machine != LA_EM_LOONGARCH)
        return (uint64_t)-1;

    /* Create new page table */
    uint64_t *new_pgtbl = la_uvm_create();
    if (!new_pgtbl) return (uint64_t)-1;

    /* Load PT_LOAD segments */
    for (int i = 0; i < eh.e_phnum; i++) {
        struct la_elf_phdr ph;
        uint64_t ph_off = eh.e_phoff + i * eh.e_phentsize;
        n = la_fs_read_file(ino, ph_off, &ph, sizeof(ph));
        if (n != sizeof(ph)) goto exec_fail;

        if (ph.p_type != LA_ELF_PROG_LOAD || ph.p_memsz == 0)
            continue;

        /* Map pages */
        uint64_t va = ph.p_vaddr & ~0xFFFUL;
        uint64_t va_end = (ph.p_vaddr + ph.p_memsz + 0xFFF) & ~0xFFFUL;
        for (; va < va_end; va += LA_PGSIZE) {
            if (la_uvm_alloc_page(new_pgtbl, va, EXE_PTE_U_RWX) == 0)
                goto exec_fail;
        }

        /* Read segment data */
        if (ph.p_filesz > 0) {
            uint64_t seg_off = 0;
            while (seg_off < ph.p_filesz) {
                uint32_t chunk = 512;
                if (chunk > ph.p_filesz - seg_off)
                    chunk = (uint32_t)(ph.p_filesz - seg_off);

                static __attribute__((aligned(8))) char tmpbuf2[512];
                n = la_fs_read_file(ino, ph.p_offset + seg_off, tmpbuf2, chunk);
                if (n != chunk) goto exec_fail;

                la_uvm_copy_in(new_pgtbl, ph.p_vaddr + seg_off, tmpbuf2, chunk);
                seg_off += chunk;
            }
        }
    }

    /* Allocate stack (2 pages for argv space) */
    uint64_t stack_top = LA_USER_STACK;
    uint64_t stack_base = stack_top - LA_PGSIZE;
    if (la_uvm_alloc_page(new_pgtbl, stack_base, EXE_PTE_U_RWX) == 0)
        goto exec_fail;

    /* ---- Set up argv on the user stack ---- */
    /* Copy argv strings from user space */
    #define MAX_EXEC_ARGS 32
    char kargv_str[MAX_EXEC_ARGS][128];
    uint64_t kargv_ptr[MAX_EXEC_ARGS];
    int argc = 0;

    if (uargv) {
        for (int i = 0; i < MAX_EXEC_ARGS; i++) {
            /* Read the argv[i] pointer from user space */
            uint32_t copied = la_copy_from_user(&kargv_ptr[i],
                                                uargv + (uint64_t)i * 8, 8);
            if (copied != 8 || kargv_ptr[i] == 0) break;

            /* Copy the string */
            la_copy_str_from_user(kargv_str[i], kargv_ptr[i], 127);
            argc++;
        }
    }

    /* Place strings at the bottom of the stack, then argv pointers above */
    uint64_t sp = stack_top;

    /* Push string data (growing downward) */
    uint64_t ustr_pos[MAX_EXEC_ARGS];
    for (int i = argc - 1; i >= 0; i--) {
        int slen = 0;
        while (kargv_str[i][slen]) slen++;
        slen++; /* include NUL */
        sp -= (uint64_t)slen;
        /* Align to 8 bytes */
        sp &= ~7ULL;
        la_uvm_copy_in(new_pgtbl, sp, kargv_str[i], (uint32_t)slen);
        ustr_pos[i] = sp;
    }

    /* Align sp for argv array */
    sp &= ~7ULL;

    /* Push argv pointers (NULL terminated) */
    sp -= 8; /* NULL terminator */
    uint64_t zero = 0;
    la_uvm_copy_in(new_pgtbl, sp, &zero, 8);

    for (int i = argc - 1; i >= 0; i--) {
        sp -= 8;
        la_uvm_copy_in(new_pgtbl, sp, &ustr_pos[i], 8);
    }

    uint64_t argv_uaddr = sp;

    /* ---- Update process ---- */
    /* TODO: free old page table */
    p->pgtbl = new_pgtbl;

    /* Reset trap frame on separate page */
    struct la_trap_frame *new_tf;
    new_tf = (struct la_trap_frame *)la_pmem_alloc();
    if (!new_tf) goto exec_fail;
    p->tf = new_tf;

    uint64_t *d = (uint64_t *)new_tf;
    uint64_t *e = (uint64_t *)(new_tf + 1);
    while (d < e) *d++ = 0;

    new_tf->era = eh.e_entry;
    new_tf->gpr[LA_GPR_SP] = sp;
    new_tf->gpr[LA_GPR_A0] = (uint64_t)argc;
    new_tf->gpr[LA_GPR_A1] = argv_uaddr;

    /* Save kernel SP for trap handler */
    la_trap_ksp = p->kstack + LA_KSTACK_SIZE;

    /* Switch page table and return to user mode */
    if (p->pgtbl) {
        la_uvm_switch(p->pgtbl);
        la_tlb_inval_all();
        la_tlb_fill_all(p->pgtbl);
    }
    la_user_return(new_tf);

    /* Never reached */
    return 0;

exec_fail:
    la_uart_puts("  exec: failed\n");
    return (uint64_t)-1;
}
